#!/usr/bin/env node

var exec = require('child_process').exec;

var parser = function(log){
  var parsed = [];

  // Array of strings
  var lines = log.split('\n');

  // Looping though each string
  for (var i = 0; i <= lines.length; i++) {
    var line = lines[i];
    // If string is empty
    if (line && line[0] === ' '){
      parsed.push(line);
    }
  }

  return parsed;
};



exec('git log -n 1000', function(err, stdout, stderr) {
  var log = parser(stdout);
  console.log(log);
});
